server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://my-database-1.c1e0aasi013u.ca-central-1.rds.amazonaws.com/shubhamdb?useSSL=false&serverTimezone=UTC
    username: admin
    password:  Rtd0f6U5sQZ5fsQARndQ
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #line 12 and 14 and 13(read again)
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false

